[package]
name = "discord-webhook-qotd-bot-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
reqwest = { version = "0.12.15", features = ["blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
