name: Build and release

on:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build for Linux
      run: cargo build --release --verbose
    - name: Build for Windows
      run: |
        rustup target add x86_64-pc-windows-gnu
        sudo apt-get install -y mingw-w64
        cargo build --release --target x86_64-pc-windows-gnu --verbose
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/release/discord-webhook-qotd-bot-rs,target/x86_64-pc-windows-gnu/release/discord-webhook-qotd-bot-rs.exe"
        allowUpdates: false
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        prerelease: false
        makeLatest: true
        name: "Release ${{ github.event.release.tag_name }}"
        discussionCategory: "New Versions"